USE AdventureWorks2017

--TABELA COM TOP 100 PRIMEIRAS PESSOAS DECRESCENTE
SELECT * FROM PERSON.PERSON
SELECT TOP (100) FirstName,LastName FROM PERSON.PERSON
ORDER BY FirstName DESC, LastName

--TABELA COM O TOP 10 PRODUTOS MAIS VENDIDOS
SELECT * FROM SALES.SalesOrderDetail
SELECT TOP (10)ProductID, LineTotal, OrderQty From Sales.SalesOrderDetail
ORDER BY LINETOTAL DESC

--APENAS ACHAR 
SELECT * FROM PERSON.Person
WHERE BusinessEntityID = 1
SELECT * FROM PERSON.EmailAddress
WHERE BusinessEntityID = 1

--TABELA COM APENAS OS EMAIL OS NOMES E O ID
SELECT PERSON.PERSON.FirstName, PERSON.EmailAddress.EmailAddress FROM PERSON.Person, PERSON.EmailAddress
WHERE PERSON.PERSON.BusinessEntityID = PERSON.EMAILADDRESS.BusinessEntityID
--ACHAR A PRIMEIRA PESSOA = ID1
AND PERSON.BusinessEntityID = 1

--TABELA COM OS PRODUTOS TOP 10 COM O NOME DOS PRODUTOS
SELECT * FROM SALES.SalesOrderDetail
SELECT TOP (10)ProductID, LineTotal, OrderQty From Sales.SalesOrderDetail
ORDER BY LINETOTAL DESC




